# Generated by Django 5.2.4 on 2025-07-14 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_region_remove_user_user_type_user_role_and_more"),
        ("products", "0002_alter_product_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="farmer",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="quantity_available",
            new_name="quantity",
        ),
        migrations.AlterField(
            model_name="product",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="accounts.region",
            ),
        ),
    ]
