# Generated by Django 5.2.4 on 2025-07-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size in acres', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_type',
            field=models.CharField(blank=True, choices=[('crop', 'Crop Farming'), ('livestock', 'Livestock'), ('mixed', 'Mixed Farming'), ('aquaculture', 'Aquaculture'), ('poultry', 'Poultry')], default='crop', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='farming_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of experience', null=True),
        ),
    ]
