# Generated by Django 5.0.4 on 2024-05-13 08:34

from django.db import migrations

def populate_regions(apps, schema_editor):
    Region = apps.get_model('accounts', 'Region')
    regions = [
        {"name": "Arusha", "code": "TZ-01"},
        {"name": "Dar es Salaam", "code": "TZ-02"},
        {"name": "Dodoma", "code": "TZ-03"},
        {"name": "Geita", "code": "TZ-27"},
        {"name": "Iringa", "code": "TZ-04"},
        {"name": "Kagera", "code": "TZ-05"},
        {"name": "Katavi", "code": "TZ-28"},
        {"name": "Kigoma", "code": "TZ-08"},
        {"name": "Kilimanjaro", "code": "TZ-09"},
        {"name": "Lindi", "code": "TZ-12"},
        {"name": "Manyara", "code": "TZ-26"},
        {"name": "Mara", "code": "TZ-13"},
        {"name": "Mbeya", "code": "TZ-14"},
        {"name": "Morogoro", "code": "TZ-16"},
        {"name": "Mtwara", "code": "TZ-17"},
        {"name": "Mwanza", "code": "TZ-18"},
        {"name": "Njombe", "code": "TZ-29"},
        {"name": "Pemba North", "code": "TZ-06"},
        {"name": "Pemba South", "code": "TZ-10"},
        {"name": "Pwani", "code": "TZ-19"},
        {"name": "Rukwa", "code": "TZ-20"},
        {"name": "Ruvuma", "code": "TZ-21"},
        {"name": "Shinyanga", "code": "TZ-22"},
        {"name": "Simiyu", "code": "TZ-30"},
        {"name": "Singida", "code": "TZ-23"},
        {"name": "Songwe", "code": "TZ-31"},
        {"name": "Tabora", "code": "TZ-24"},
        {"name": "Tanga", "code": "TZ-25"},
        {"name": "Zanzibar North", "code": "TZ-07"},
        {"name": "Zanzibar South", "code": "TZ-11"},
        {"name": "Zanzibar West", "code": "TZ-15"},
    ]
    for region_data in regions:
        Region.objects.create(**region_data)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_regions),
    ]
