# Generated by Django 5.2.4 on 2025-07-14 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_data_migration_add_mbeya_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_type",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("farmer", "Farmer"),
                    ("supplier", "Supplier"),
                    ("buyer", "Buyer"),
                ],
                default="buyer",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.region",
            ),
        ),
    ]
