# Generated by Django 3.2.13 on 2024-07-15 12:00

from django.db import migrations

def populate_regions(apps, schema_editor):
    Region = apps.get_model('accounts', 'Region')
    regions = [
        'Arusha', 'Dar es Salaam', 'Dodoma', 'Geita', 'Iringa', 'Kagera',
        'Katavi', 'Kigoma', 'Kilimanjaro', 'Lindi', 'Manyara', 'Mara',
        'Mbeya', 'Morogoro', 'Mtwara', 'Mwanza', 'Njombe', 'Pemba North',
        'Pemba South', 'Pwani', 'Rukwa', 'Ruvuma', 'Shinyanga', 'Simiyu',
        'Singida', 'Songwe', 'Tabora', 'Tanga', 'Unguja North',
        'Unguja South', 'Zanzibar Urban West'
    ]
    for region_name in regions:
        Region.objects.create(name=region_name, code=region_name[:3].upper())

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_regions),
    ]
