# Generated by Django 5.2.4 on 2025-07-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_farmerprofile_farm_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
        migrations.DeleteModel(
            name='SupplierProfile',
        ),
    ]
