# Generated by Django 5.2.4 on 2025-07-15 14:33

from django.db import migrations

def add_mbeya_region(apps, schema_editor):
    Region = apps.get_model('accounts', 'Region')
    Region.objects.create(name='mbeya')

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_mbeya_region),
    ]
