# Generated by Django 5.2.4 on 2025-07-14 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_region_remove_user_user_type_user_role_and_more"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_status_142af0_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_farmer__29e9d6_idx",
        ),
        migrations.RemoveField(
            model_name="product",
            name="expiry_date",
        ),
        migrations.RemoveField(
            model_name="product",
            name="harvest_date",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_organic",
        ),
        migrations.RemoveField(
            model_name="product",
            name="min_order_quantity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="origin_region",
        ),
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="product",
            name="status",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="product",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="product",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="", upload_to="products/"),
        ),
        migrations.AddField(
            model_name="product",
            name="region",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="accounts.region",
            ),
        ),
    ]
