# Generated by Django 5.2.4 on 2025-07-26 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0002_category_slug_product_is_active_product_is_featured_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="freshness_indicator",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="harvest_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="quality_grade",
            field=models.CharField(
                blank=True,
                choices=[("A", "Grade A"), ("B", "Grade B"), ("C", "Grade C")],
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="ProductCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="certificates/")),
                ("issued_by", models.CharField(max_length=100)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
