# Generated by Django 5.2.4 on 2025-07-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_stock_quantity_seasonalproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="bulk_pricing",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
