# Generated by Django 5.2.4 on 2025-07-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_add_farmer_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_schedule",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
    ]
