# Generated by Django 5.2.4 on 2025-07-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesAnalytics',
        ),
    ]
